# this wil initialize the configuration types in the configuration storage
commerce_multisafepay_payments.settings:
  type: commerce_payment_gateway_configuration
  mapping:
    test_api_key:
      type: string
      label: 'Test API Key'
    live_api_key:
      type: string
      label: 'Live API Key'
    account_type:
      type: string
      label: 'Account Type'
    seconds_active:
      type: string
      label: 'Seconds Alive'
    debug:
      type: string
      label: 'Debug mode'
commerce_payment.commerce_payment_gateway.plugin.msp_generic_gateway:
  type: commerce_payment_gateway_configuration
  mapping:
    generic_gateway_code:
      type: string
      label: 'Gateway code'
